### ISSUE TITLE
Svelte 4 support?

### ISSUE THREAD

**Issue by NickantX** [nathanfaucett/svelte-slate#10]
Hey, any plans to update this package to support svelte 4? I tested it out with npm install --force and it seemed to work fine, although I haven't tested it super in depth. Svelte 3 no longer receives updates, so it would be helpful to have official support for Svelte 4.

**Comment by nathanfaucett** [comment]
I have updated the peer dependency for svelte to `>=3` and updated/tested the package with svelte 4, let me know if this does not resolve the issue and I will reopen it.
