### ISSUE TITLE
Toolbar not appearing in sample editor

### ISSUE THREAD

**Issue by arsalan-menhaj** [nathanfaucett/svelte-slate#6]
Hello,

I was looking at the [source code](https://github.com/nathanfaucett/svelte-slate/blob/main/src/routes/plugins/+page.svelte) for the [sample editor](https://nathanfaucett.github.io/svelte-slate/plugins), and I noticed that there is a Toolbar child component that seems to not be rendered anywhere. Is there something I'm missing?

Thanks in advance.

**Comment by nathanfaucett** [comment]
Hey @arsalan-menhaj the toolbar is rendered when text is selected or you click and hold for more than a second, very similar to medium's toolbar if you have ever used that.

**Comment by nathanfaucett** [comment]
closing this as it is not something that needs fixing
